# -*- coding: utf-8 -*-
#
from recommonmark.parser import CommonMarkParser

source_parsers = {
    '.md': CommonMarkParser,
}

source_suffix = ['.md']

# -- General configuration -----------------------------------------------------

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'HoneyPy'
copyright = u'foospidy'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'en'
